#!/usr/bin/env sh
if [ -f "$(dirname -- "$0")/_/husky.sh" ]; then
  . "$(dirname -- "$0")/_/husky.sh"
elif [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
fi

if [ "$OS" = "Windows_NT" ] || [ "$MSYSTEM" ] || [ "$TERM_PROGRAM" = "vscode" ]; then
  pnpm dlx git-cz --hook || true
elif [ -t 0 ] && [ -r /dev/tty ]; then
  exec < /dev/tty && pnpm dlx git-cz --hook || true
else
  pnpm dlx git-cz --hook || true
fi